type: object
properties: 
  uid:
    type: number
  lastFmScrobblingEnabled:
    type: boolean
    example: false
  facebookScrobblingEnabled:
    type: boolean
    example: false
  shuffleEnabled:
    type: boolean
    example: false
  addNewTrackOnPlaylistTop:
    type: boolean
    example: false
  volumePercents:
    type: boolean
    example: 75
  userMusicVisibility:
    type: string
    example: "PUBLIC"
  userSocialVisibility:
    type: string
    example: "PUBLIC"
  adsDisabled:
    type: boolean
    example: true
  modified:
    type: string
    modified: "2019-04-14T14:55:50+00:00"
  rbtDisabled:
    type: string
  theme: 
    type: string
    description: Тема оформления.
    example: "black"
  promosDisabled:
    type: boolean
    example: true
  autoPlayRadio:
    type: boolean
    example: true
  syncQueueEnabled:
    type: boolean
    example: false