openapi: 3.0.1
info:
  title: Yandex Music Api
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  version: 1.0.0
servers:
- url: https://api.music.yandex.net:443/
- url: http://api.music.yandex.net:443/
paths:
  /feed:
    get:
      responses:
        200:
          description: Ok
          content: {}
        400:
          description: Bad request
          content: {}
components: {}
