openapi: 3.0.1
info:
  title: Yandex Music Api
  description: 'Swagger документация для Yandex Music API.'
  version: 1.0.0
servers:
- url: https://api.music.yandex.net:443/
- url: http://api.music.yandex.net:443/
paths:
  /feed:
    get:
      responses:
        200:
          description: Ok
          content: {}
  /albums/{albumId}/:
    parameters:
      - in: path
        name: albumId
        schema:
          type: number
        required: true
        example: 7019818
    get:
      responses:
        200:
          description: Ok
          content: {}
  /albums/{albumId}/with-tracks:
    parameters:
      - in: path
        name: albumId
        schema:
          type: number
        required: true
        example: 7019818
    get:
      responses:
        200:
          description: Ok
          content: {}

components: {}
